name: Learning as I go
description: Learning GitHub Actions by creating one
author: sjhawke - just me

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  milliseconds:
    description: Dummy wait time in milliseconds
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: Whatever it does

runs:
  using: node24
  main: dist/index.js
